{% set name = "pymc3" %}
{% set version = "3.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/{{name}}/archive/v{{version}}.tar.gz
  sha256: 1af9ecf29b5c2a916e55f75ec96c3dede575de6052efd618af44d306c5928402

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - theano >=1.0.0
    - numpy >=1.11.0
    - scipy >=0.12.0
    - matplotlib >=1.5.0
    - pandas >=0.18.0
    - patsy >=0.4.0
    - joblib >=0.9
    - tqdm >=4.8.4
    - six >=1.10.0
    - h5py >=2.7.0
    - enum34 >=1.1.6  # [py<34]

test:
  imports:
    - pymc3
    - pymc3.backends
    - pymc3.distributions
    - pymc3.examples
    - pymc3.external
    - pymc3.glm
    - pymc3.gp
    - pymc3.plots
    - pymc3.step_methods
    - pymc3.step_methods.hmc
    - pymc3.tests
    - pymc3.tuning
    - pymc3.variational

  requires:
    - pytest

about:
  home: http://github.com/pymc-devs/pymc3
  license: Apache-2.0
  summary: 'Probabilistic Programming in Python.'
  license_family: Apache

extra:
  recipe-maintainers:
    - ericmjl
    - springcoil
