{% set version = "3.11.2" %}

package:
  name: pymc3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymc3/pymc3-{{ version }}.tar.gz
  sha256: d3b93c8923ae8c8107c5adfd22f7c37fa0849a00a9723e0e0a0ca6afb582d6c3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - theano >=1.0.4
    - numpy >=1.13.0
    - scipy >=0.18.1
    - pandas >=0.18.0
    - patsy >=0.4.0
    - tqdm >=4.8.4
    - h5py >=2.7.0

test:
  imports:
    - pymc3
    - pymc3.backends
    - pymc3.distributions
    - pymc3.examples
    - pymc3.glm
    - pymc3.gp
    - pymc3.step_methods
    - pymc3.tests
    - pymc3.tuning
    - pymc3.variational

  requires:
    - pytest

about:
  home: http://github.com/pymc-devs/pymc3
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Probabilistic Programming in Python'

extra:
  recipe-maintainers:
    - ericmjl
    - springcoil
    - twiecki
