{% set version = "3.11.1" %}

package:
  name: pymc3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymc3/pymc3-{{ version }}.tar.gz
  sha256: 501d48b9f5d033678de7a5918b9d055a6806adf84fe16a5a9d65eaa2dc71acd8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - arviz >=0.11.0
    - dill
    - fastprogress >=0.2.0
    - numpy >=1.15.0
    - pandas >=0.24.0
    - patsy >=0.5.1
    - scipy >=1.2.0
    - theano-pymc ==1.1.0
    - typing-extensions >=3.7.4
    - mkl-service

test:
  imports:
    - pymc3
    - pymc3.backends
    - pymc3.distributions
    - pymc3.glm
    - pymc3.gp
    - pymc3.step_methods
    - pymc3.tests
    - pymc3.tuning
    - pymc3.variational
    - pymc3.ode
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pymc-devs/pymc3
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Probabilistic Programming in Python

extra:
  recipe-maintainers:
    - ericmjl
    - springcoil
    - twiecki
