{% set version = "3.11.0" %}

package:
  name: pymc3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymc3/pymc3-{{ version }}.tar.gz
  sha256: 8ddac7f4b71bebcb86d33f07f04183600e50018e458a12813862bd8df0abafe9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - arviz >=0.9.0
    - dill
    - fastprogress >=0.2.0
    - numpy >=1.13.0
    - pandas >=0.18.0
    - patsy >=0.5.1
    - scipy >=0.18.1
    - theano-pymc ==1.0.11
    - typing-extensions >=3.7.4
    - mkl-service

test:
  imports:
    - pymc3
    - pymc3.backends
    - pymc3.distributions
    - pymc3.examples
    - pymc3.glm
    - pymc3.gp
    - pymc3.step_methods
    - pymc3.tests
    - pymc3.tuning
    - pymc3.variational
    - pymc3.ode
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pymc-devs/pymc3
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Probabilistic Programming in Python

extra:
  recipe-maintainers:
    - ericmjl
    - springcoil
    - twiecki
