{% set name = "pymc3" %}
{% set version = "3.1rc3" %}
{% set md5 = "8751b2937c84a0f4801841f88b3cee26dc48d04b2ddc6d94e99544cb04ccff57" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn:  {{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ sha256 }}

build:
  number: 0
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.11.0
    - scipy >=0.12.0
    - matplotlib >=1.5.0
    - theano >=0.9.0
    - pandas >=0.18.0
    - patsy >=0.4.0
    - joblib >=0.9
    - tqdm >=4.8.4
    - h5py >=2.7.0

test:
  imports:
    - pymc3
    - pymc3.backends
    - pymc3.distributions
    - pymc3.examples
    - pymc3.glm
    - pymc3.step_methods
    - pymc3.tests
    - pymc3.tuning
    - pymc3.variational

  requires:
    - nose

about:
  home: http://github.com/pymc-devs/pymc3
  license: AFL-3.0
  summary: 'Probabilistic Programming in Python.'
  license_family: Apache

extra:
  recipe-maintainers:
    - ericmjl
    - springcoil
