travis:
  secure:
    BINSTAR_TOKEN: TrAc/cJ71j4el+bg5HCU1wHYxSjhQJvRi4H4UYyXnksnIN8pjnnTE71iuBTeXFkDrhITSbpcgm/Gj9+NPBc/6rZfDIiYnvJYiHXd+k+iaixgrWgzjrAyzDSDZ9aQjACcIXJv/ilIGOvWcqwvnoWUmtjs8nreUECg03fJPHKjfDUTAlCRy9uZWboXR6bcgxuGIWre5z98qY5ZuwyKulwPu2rrH5pdP/wPgmzq5Zs/ykdhGEzr0hYw73cuJIOXLAbIuOqkRN5ihRPdamDtqUPmk+rPMhOBAuwlOGForZD0EXOKoXDQo2Xc8b9Egq5ArJg4mv0ltMkU1CpAIW0V0vFLW1NcHDsfufCJtbMnx9rOQRwnsJjK56ihejFS9tP+Jt4liItc6T4cPCPwjgadWvYQTAeU5SHV4zwri/7eLKT23t7f8vBwuu435lXUzXVifnVi2wmc3vV19w4uJQogqhAQDzddapoVJBUQIdDLaZrZOfquXgdxNyNWmSSb4ML+RhoTaz2/rruY3fE9LLE+b2CyiCntWsQm5lTE1+leg8ZBlfx8rr50csAYqXCTvKjYh/EiaWn8emDUWS87RASAJflSjxWIPnogwGTQ0QGaj6edKoeyN2JD/vccPeATRsa37angEk79QJ+ql1OZMDaWaJFD2wESx9QiT76Oy/6hVLW69Uw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
